/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfessoraRouteImport } from './routes/professora'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfessoraAlertasRouteImport } from './routes/professora_.alertas'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminProfessorasRouteImport } from './routes/admin.professoras'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminAlertasRouteImport } from './routes/admin.alertas'
import { Route as ProfessoraAlunoIdRouteImport } from './routes/professora_.aluno.$id'
import { Route as AdminAlunosInativosRouteImport } from './routes/admin.alunos_.inativos'
import { Route as AdminAlunosIdRouteImport } from './routes/admin.alunos_.$id'

const ProfessoraRoute = ProfessoraRouteImport.update({
  id: '/professora',
  path: '/professora',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfessoraAlertasRoute = ProfessoraAlertasRouteImport.update({
  id: '/professora_/alertas',
  path: '/professora/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessorasRoute = AdminProfessorasRouteImport.update({
  id: '/professoras',
  path: '/professoras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)
const ProfessoraAlunoIdRoute = ProfessoraAlunoIdRouteImport.update({
  id: '/professora_/aluno/$id',
  path: '/professora/aluno/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlunosInativosRoute = AdminAlunosInativosRouteImport.update({
  id: '/alunos_/inativos',
  path: '/alunos/inativos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosIdRoute = AdminAlunosIdRouteImport.update({
  id: '/alunos_/$id',
  path: '/alunos/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/professora': typeof ProfessoraRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/professoras': typeof AdminProfessorasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/professora/alertas': typeof ProfessoraAlertasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alunos/$id': typeof AdminAlunosIdRoute
  '/admin/alunos/inativos': typeof AdminAlunosInativosRoute
  '/professora/aluno/$id': typeof ProfessoraAlunoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/professora': typeof ProfessoraRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/professoras': typeof AdminProfessorasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/professora/alertas': typeof ProfessoraAlertasRoute
  '/admin': typeof AdminIndexRoute
  '/admin/alunos/$id': typeof AdminAlunosIdRoute
  '/admin/alunos/inativos': typeof AdminAlunosInativosRoute
  '/professora/aluno/$id': typeof ProfessoraAlunoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/professora': typeof ProfessoraRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/professoras': typeof AdminProfessorasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/professora_/alertas': typeof ProfessoraAlertasRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alunos_/$id': typeof AdminAlunosIdRoute
  '/admin/alunos_/inativos': typeof AdminAlunosInativosRoute
  '/professora_/aluno/$id': typeof ProfessoraAlunoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/professora'
    | '/admin/alertas'
    | '/admin/alunos'
    | '/admin/calendario'
    | '/admin/professoras'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/professora/alertas'
    | '/admin/'
    | '/admin/alunos/$id'
    | '/admin/alunos/inativos'
    | '/professora/aluno/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/professora'
    | '/admin/alertas'
    | '/admin/alunos'
    | '/admin/calendario'
    | '/admin/professoras'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/professora/alertas'
    | '/admin'
    | '/admin/alunos/$id'
    | '/admin/alunos/inativos'
    | '/professora/aluno/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/professora'
    | '/admin/alertas'
    | '/admin/alunos'
    | '/admin/calendario'
    | '/admin/professoras'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/professora_/alertas'
    | '/admin/'
    | '/admin/alunos_/$id'
    | '/admin/alunos_/inativos'
    | '/professora_/aluno/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProfessoraRoute: typeof ProfessoraRoute
  ProfessoraAlertasRoute: typeof ProfessoraAlertasRoute
  ProfessoraAlunoIdRoute: typeof ProfessoraAlunoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professora': {
      id: '/professora'
      path: '/professora'
      fullPath: '/professora'
      preLoaderRoute: typeof ProfessoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/professora_/alertas': {
      id: '/professora_/alertas'
      path: '/professora/alertas'
      fullPath: '/professora/alertas'
      preLoaderRoute: typeof ProfessoraAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professoras': {
      id: '/admin/professoras'
      path: '/professoras'
      fullPath: '/admin/professoras'
      preLoaderRoute: typeof AdminProfessorasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/professora_/aluno/$id': {
      id: '/professora_/aluno/$id'
      path: '/professora/aluno/$id'
      fullPath: '/professora/aluno/$id'
      preLoaderRoute: typeof ProfessoraAlunoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alunos_/inativos': {
      id: '/admin/alunos_/inativos'
      path: '/alunos/inativos'
      fullPath: '/admin/alunos/inativos'
      preLoaderRoute: typeof AdminAlunosInativosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos_/$id': {
      id: '/admin/alunos_/$id'
      path: '/alunos/$id'
      fullPath: '/admin/alunos/$id'
      preLoaderRoute: typeof AdminAlunosIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminProfessorasRoute: typeof AdminProfessorasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlunosIdRoute: typeof AdminAlunosIdRoute
  AdminAlunosInativosRoute: typeof AdminAlunosInativosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminAlunosRoute: AdminAlunosRoute,
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminProfessorasRoute: AdminProfessorasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlunosIdRoute: AdminAlunosIdRoute,
  AdminAlunosInativosRoute: AdminAlunosInativosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProfessoraRoute: ProfessoraRoute,
  ProfessoraAlertasRoute: ProfessoraAlertasRoute,
  ProfessoraAlunoIdRoute: ProfessoraAlunoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
